# Generated by Django 5.2.10 on 2026-01-16 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.IntegerField(unique=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(default='Unknown', max_length=10)),
                ('marital_status', models.CharField(default='Unknown', max_length=20)),
                ('education_field', models.CharField(blank=True, max_length=100, null=True)),
                ('distance_from_home', models.PositiveIntegerField(default=0)),
                ('attrition', models.CharField(default='No', max_length=5)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('CDI', 'Permanent'), ('CDD', 'Fixed-term'), ('INTERNSHIP', 'Internship'), ('APPRENTICESHIP', 'Apprenticeship')], default='CDI', max_length=20)),
                ('weekly_hours', models.PositiveIntegerField(default=35)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ExitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_date', models.DateField()),
                ('reason', models.CharField(choices=[('Career Change', 'Changement de carrière'), ('Better Offer', 'Meilleure opportunité'), ('Personal Reasons', 'Raisons personnelles'), ('Retirement', 'Retraite')], max_length=100)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_info', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_level', models.PositiveIntegerField(default=1)),
                ('monthly_income', models.PositiveIntegerField(default=0)),
                ('business_travel', models.CharField(default='Non-Travel', max_length=50)),
                ('overtime', models.CharField(default='No', max_length=5)),
                ('years_at_company', models.PositiveIntegerField(default=0)),
                ('years_since_last_promotion', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.department')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='hr.employee')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.jobrole')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_rating', models.PositiveIntegerField(default=3)),
                ('percent_salary_hike', models.PositiveIntegerField(default=0)),
                ('training_times_last_year', models.PositiveIntegerField(default=0)),
                ('review_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SatisfactionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_satisfaction', models.PositiveIntegerField(default=3)),
                ('environment_satisfaction', models.PositiveIntegerField(default=3)),
                ('relationship_satisfaction', models.PositiveIntegerField(default=3)),
                ('work_life_balance', models.PositiveIntegerField(default=3)),
                ('survey_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_surveys', to='hr.employee')),
            ],
        ),
    ]
