# Generated by Django 6.0.1 on 2026-02-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='internal_note',
            field=models.TextField(blank=True, help_text='Note confidentielle RH', null=True),
        ),
    ]
