# Generated by Django 5.2.10 on 2026-01-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_firstname_employee_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='lastname',
        ),
    ]
