# Generated by Django 5.2.10 on 2026-01-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_remove_employee_firstname_remove_employee_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='firstname',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='lastname',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
